//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneticTranslator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class PhoneticTranslator : global::System.Configuration.ApplicationSettingsBase {
        
        private static PhoneticTranslator defaultInstance = ((PhoneticTranslator)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PhoneticTranslator())));
        
        public static PhoneticTranslator Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DictionariesLocation {
            get {
                return ((string)(this["DictionariesLocation"]));
            }
            set {
                this["DictionariesLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PhoneticDictPath {
            get {
                return ((string)(this["PhoneticDictPath"]));
            }
            set {
                this["PhoneticDictPath"] = value;
            }
        }
    }
}
